#!/bin/bash


kill $(paux firefox | grep foxprox | awk '{print $2}')
rm -r ~/.cache/mozilla

proxyfile='/home/must4rd/.mozilla/firefox/*.foxprox/prefs.js'
oldip=$(cat $proxyfile | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep 10.252. | sort -u)

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

if [ -z "$1"]
then
    echo "Enter IP:"
    read newip
else
    if valid_ip $1
    then 
        newip=$1
    else
        newip=10.252.$1
    fi
fi

if valid_ip $newip
then
    sed -i -r  "s/$oldip/$newip/g" $proxyfile 
    firefox -P foxprox --new-window octo.octo
else 
    echo "no valid ip...tschau"
fi
