#!/bin/bash


killall firefox
rm -r ~/.cache/mozilla

proxyfile='/home/must4rd/.mozilla/firefox/*.foxprox/prefs.js'
oldip=$(cat $proxyfile | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep 10.252. | sort -u)

if [ -z $1];
then
    echo "Enter IP:"
    read newip
else
    newip=10.252.$1
#    newip=$1
fi

echo $oldip
echo $newip
    sed -i -r  "s/$oldip/$newip/g" $proxyfile 
firefox -P foxprox --new-window octo.octo &
# sleep 3
# xdotool mousemove 3250 480 click 1
