#!/bin/bash


# This script will test if you have given a leap year or not.
killall firefox
rm -r ~/.cache/mozilla
proxyfile='/home/must4rd/.mozilla/firefox/jdg0rb3p.foxprox/prefs.js'
#proxyfile='/home/must4rd/.mozilla/firefox/zt5qfzv9.Proxy/prefs.js'
oldip=$(cat $proxyfile | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep 10.252. | sort -u)
if [ -z "$1"]
then
    echo "Enter IP:"
    read newip
else
    newip=$1
fi

    sed -i -r  "s/$oldip/$newip/g" $proxyfile 
firefox -P foxprox --new-window octo.octo
