#! /bin/sh

#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\  
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\ 
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/ 
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/

###################
## configuration ##
###################

## workspace name
## font needed wuncon-siji
bspc monitor HDMI-1 -d '' ''
bspc monitor DVI-I-2-1 -d '' '' '' '' ''
bspc monitor eDP-1 -d '' ''
# bspc monitor HDMI-1-1 -d '' ''
# bspc monitor DVI-I-2-1 -d '' '' '' '' ''
# bspc monitor eDP-1-1 -d '' ''
## bspc monitor DP-2-d 'I' '' '' '' '' '' '' ''

## common bspwm configuration
bspc config border_width        1
bspc config window_gap         	16
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true 
bspc config focus_follows_pointer true
bspc config top_padding 24


## color settings
bspc config focused_border_color "#ecdece" 
bspc config normal_border_color "#25201f"


##################
## window rules ##
##################

## workspace 1 (labs)
bspc rule -a URxvt desktop='^1' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

## workspace 2 (web browsers)

## workspace 3 (file-manager)
bspc rule -a Pidgin desktop='^3' follow=on focus=on
bspc rule -a Vivaldi-stable desktop='^3' follow=on focus=on

## workspace 4 (text-editors)
bspc rule -a firefox desktop='^4' follow=on focus=on
bspc rule -a Chromium desktop='^4' follow=on focus=on
bspc rule -a Opera desktop='^4' follow=on focus=on
bspc rule -a Support.py desktop='^4' state=floating follow=on

## workspace 5 (graphic-utilities)
bspc rule -a TeamViewer desktop='^5' follow=on focus=on state=floating
bspc rule -a Geany desktop='^5' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^5' follow=on focus=on
bspc rule -a libreoffice desktop='^5' follow=on focus=on
bspc rule -a Soffice desktop='^5' follow=on focus=on
bspc rule -a libreoffice-base desktop='^5' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^5' follow=on focus=on
bspc rule -a libreoffice-draw desktop='^5' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^5' follow=on focus=on
bspc rule -a libreoffice-math desktop='^5' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^5' follow=on focus=on
bspc rule -a Wps desktop='^5' follow=on focus=on
bspc rule -a Et desktop='^5' follow=on focus=on
bspc rule -a Wpp desktop='^5' follow=on focus=on

## workspace 6 (multimedia)
bspc rule -a Audacity desktop='^6' follow=on focus=on
bspc rule -a Vlc desktop='^6' follow=on focus=on
bspc rule -a mpv desktop='^6' follow=on focus=on
bspc rule -a Ghb desktop='^6' follow=on focus=on
bspc rule -a Xfburn desktop='^6' follow=on focus=on
bspc rule -a Kodi desktop='^6' follow=on focus=on

## workspace 7 (graphics-editors)
bspc rule -a Gimp desktop='^7' follow=on focus=on
bspc rule -a Spotify desktop='^7' follow=on focus=on
bspc rule -a spotify desktop='^7' follow=on focus=on
bspc rule -a Spotify:* desktop='^7' follow=on focus=on
bspc rule -a *:Spotify desktop='^7' follow=on focus=on
bspc rule -a Gimp-2.8 desktop='^7' follow=on focus=on
bspc rule -a Inkscape desktop='^7' follow=on focus=on
bspc rule -a Spotify desktop='^7' follow=on focus=on
bspc rule -a *:pavucontrol desktop='^7' follow=on

## workspace 8 (system-settings)
bspc rule -a Lxappearance desktop='^8' state=floating follow=on
bspc rule -a Xfce4-settings-manager desktop='^8' state=floating follow=on
bspc rule -a Lightdm-gtk-greeter-settings desktop='^8' state=floating follow=on
bspc rule -a System-config-printer.py desktop='^8' state=floating follow=on

## need to be floating
bspc rule -a Audacious state=floating follow=on
bspc rule -a yakuake state=floating follow=on
bspc rule -a Viewnior state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a Gpicview state=floating follow=on
bspc rule -a Whatsie state=floating follow=on
bspc rule -a whatsapp-nativefier state=floating follow=on
bspc rule -a whats-app-nativefier-d52542 state=floating follow=on
bspc rule -a clipit desktop='^3' follow=on focus=on
bspc rule -a clipit:* desktop='^3' follow=on focus=on
bspc rule -a *:clipit desktop='^3' follow=on focus=on
bspc rule -a Galculator state=floating follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a wicd-client.py state=floating follow=on
bspc rule -a Wicd-client.py state=floating follow=on
bspc rule -a Pythontest.py state=floating follow=on
bspc rule -a keepassxc  state=floating follow=on
bspc rule -a Guake  state=floating follow=on
bspc rule -a guake  state=floating follow=on
bspc rule -a twistifier-nativefier-790d57  state=floating follow=on



## don't manage my conky & systemtray :/
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

###############
## autostart ##
###############

# Load bitmap fonts
xset fp+ ~/.fonts/misc &

## reload compton
pkill compton
compton -b &

# system tray
pkill stalonetray
stalonetray &

# network applet
nm-applet &

# clipboard manager
pkill clipit
clipit &

# volume icon
# pkill volumeicon
# volumeicon &

# pasystray
pkill pasystray
pasystray &

# keybind daemon
pkill sxhkd
sxhkd &

## music is my only friend :(
mpd &

## reload the xsettingsd, a minimal x settings daemon
pkill xsettingsd
xsettingsd &

## set the wallpaper
feh --bg-fill ~/.wallpaper.jpg

## load dunst
pkill dunst
dunst &

## guake dropdown term
pkill guake
guake &

## reload the cursor theme
xsetroot -cursor_name left_ptr

## load panel script
pkill panel-bspwm
pkill panel-bspwm2
pkill panel-bspwm3
pkill panel-bspwm4
#panel-bspwm &
testpanel &
panel-bspwm4 &

xmodmap /home/must4rd/.Xmodmap &
